module.exports.descriptors = [
  'Independent',
  'First Lake',
  'Creekwood',
  'Ronald',
  'Cascade',
  'Second Timothy',
  'Golden',
  'Redwood',
  'Fundamental',
  'Maple',
  'Misty',
  'Elk',
  'Grassy Slope',
  'Ocean',
  'Sea',
  'Sky',
  'Dusty',
  'Diamond',
];

module.exports.places = [
  'Baptist Church',
  'Presbyterian Church',
  'Baptist Church',
  'Presbyterian Church',
  'Baptist Church',
  'Presbyterian Church',
  'Baptist Church',
  'Presbyterian Church',
  'Baptist Church',
  'Presbyterian Church',
  'Baptist Church',
  'Presbyterian Church',
  'Baptist Church',
  'Presbyterian Church',
  'Baptist Church',
  'Presbyterian Church',
  'Baptist Church',
  'Presbyterian Church',
  'Baptist Church',
  'Presbyterian Church',
  'Baptist Church',
];
